-- CREATE TABLES
CREATE TABLE CATEGORIES (
	CATEGORY_ID INT PRIMARY KEY,
	CATEGORY_NAME VARCHAR (255) NOT NULL
);
COMMENT ON COLUMN CATEGORIES.CATEGORY_ID IS 'รหัสประเภท';
COMMENT ON COLUMN CATEGORIES.CATEGORY_NAME IS 'ชื่อประเภท';

CREATE TABLE BRANDS (
	BRAND_ID INT PRIMARY KEY,
	BRAND_NAME VARCHAR (255) NOT NULL
);
COMMENT ON COLUMN BRANDS.BRAND_ID IS 'รหัสยี่ห้อ';
COMMENT ON COLUMN BRANDS.BRAND_NAME IS 'ชื่อยี่ห้อ';

CREATE TABLE PRODUCTS (
	PRODUCT_ID INT PRIMARY KEY,
	PRODUCT_NAME VARCHAR (255) NOT NULL,
	BRAND_ID INT NOT NULL,
	CATEGORY_ID INT NOT NULL,
	MODEL_YEAR INT NOT NULL,
	LIST_PRICE DECIMAL (10, 2) NOT NULL,
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (CATEGORY_ID),
	FOREIGN KEY (BRAND_ID) REFERENCES BRANDS (BRAND_ID)
);
COMMENT ON COLUMN PRODUCTS.PRODUCT_ID IS 'รหัสสินค้า';
COMMENT ON COLUMN PRODUCTS.PRODUCT_NAME IS 'ชื่อสินค้า';
COMMENT ON COLUMN PRODUCTS.BRAND_ID IS 'รหัสยี่ห้อ';
COMMENT ON COLUMN PRODUCTS.CATEGORY_ID IS 'รหัสประเภท';
COMMENT ON COLUMN PRODUCTS.MODEL_YEAR IS 'ปีรุ่น';
COMMENT ON COLUMN PRODUCTS.LIST_PRICE IS 'ราคาต่อหน่วย';

CREATE TABLE CUSTOMERS (
	CUSTOMER_ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR (255) NOT NULL,
	LAST_NAME VARCHAR (255) NOT NULL,
	PHONE VARCHAR (25),
	EMAIL VARCHAR (255) NOT NULL,
	STREET VARCHAR (255),
	CITY VARCHAR (50),
	STATE VARCHAR (25),
	ZIP_CODE VARCHAR (5)
);
COMMENT ON COLUMN CUSTOMERS.CUSTOMER_ID IS 'รหัสลูกค้า';
COMMENT ON COLUMN CUSTOMERS.FIRST_NAME IS 'ชื่อจริง';
COMMENT ON COLUMN CUSTOMERS.LAST_NAME IS 'นามสกุล';
COMMENT ON COLUMN CUSTOMERS.PHONE IS 'เบอร์โทรศัพท์';
COMMENT ON COLUMN CUSTOMERS.EMAIL IS 'อีเมล';
COMMENT ON COLUMN CUSTOMERS.STREET IS 'ที่อยู่';
COMMENT ON COLUMN CUSTOMERS.CITY IS 'เมือง';
COMMENT ON COLUMN CUSTOMERS.STATE IS 'รัฐ';
COMMENT ON COLUMN CUSTOMERS.ZIP_CODE IS 'รหัสไปรษณีย์';

CREATE TABLE STORES (
	STORE_ID SERIAL PRIMARY KEY,
	STORE_NAME VARCHAR (255) NOT NULL,
	PHONE VARCHAR (25),
	EMAIL VARCHAR (255),
	STREET VARCHAR (255),
	CITY VARCHAR (255),
	STATE VARCHAR (10),
	ZIP_CODE VARCHAR (5)
);
COMMENT ON COLUMN STORES.STORE_ID IS 'รหัสร้านค้า';
COMMENT ON COLUMN STORES.STORE_NAME IS 'ชื่อร้านค้า';
COMMENT ON COLUMN STORES.PHONE IS 'เบอร์โทรศัพท์';
COMMENT ON COLUMN STORES.EMAIL IS 'อีเมล';
COMMENT ON COLUMN STORES.STREET IS 'ที่อยู่';
COMMENT ON COLUMN STORES.CITY IS 'เมือง';
COMMENT ON COLUMN STORES.STATE IS 'รัฐ';
COMMENT ON COLUMN STORES.ZIP_CODE IS 'รหัสไปรษณีย์';

CREATE TABLE STAFFS (
	STAFF_ID INT PRIMARY KEY,
	FIRST_NAME VARCHAR (50) NOT NULL,
	LAST_NAME VARCHAR (50) NOT NULL,
	EMAIL VARCHAR (255) NOT NULL UNIQUE,
	PHONE VARCHAR (25),
	ACTIVE INT NOT NULL,
	STORE_ID INT NOT NULL,
	MANAGER_ID INT,
	FOREIGN KEY (STORE_ID) REFERENCES STORES (STORE_ID),
	FOREIGN KEY (MANAGER_ID) REFERENCES STAFFS (STAFF_ID)
);
COMMENT ON COLUMN STAFFS.STAFF_ID IS 'รหัสพนักงาน';
COMMENT ON COLUMN STAFFS.FIRST_NAME IS 'ชื่อจริง';
COMMENT ON COLUMN STAFFS.LAST_NAME IS 'นามสกุล';
COMMENT ON COLUMN STAFFS.EMAIL IS 'อีเมล';
COMMENT ON COLUMN STAFFS.PHONE IS 'เบอร์โทรศัพท์';
COMMENT ON COLUMN STAFFS.ACTIVE IS 'สถานะ';
COMMENT ON COLUMN STAFFS.STORE_ID IS 'รหัสร้านค้า';
COMMENT ON COLUMN STAFFS.MANAGER_ID IS 'รหัสพนักงานหัวหน้า';

CREATE TABLE ORDERS (
	ORDER_ID INT PRIMARY KEY,
	CUSTOMER_ID INT,
	ORDER_STATUS INT NOT NULL,
	ORDER_DATE DATE NOT NULL,
	REQUIRED_DATE DATE NOT NULL,
	SHIPPED_DATE DATE,
	STORE_ID INT NOT NULL,
	STAFF_ID INT NOT NULL,
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID),
	FOREIGN KEY (STORE_ID) REFERENCES STORES (STORE_ID),
	FOREIGN KEY (STAFF_ID) REFERENCES STAFFS (STAFF_ID)
);
COMMENT ON COLUMN ORDERS.ORDER_ID IS 'รหัสคำสั่งซื้อ';
COMMENT ON COLUMN ORDERS.CUSTOMER_ID IS 'รหัสลูกค้า';
COMMENT ON COLUMN ORDERS.ORDER_STATUS IS 'สถานะ : 1 = รอชำระเงิน; 2 = กำลังดำเนินการ; 3 = ยกเลิก; 4 = สำเร็จ';
COMMENT ON COLUMN ORDERS.ORDER_DATE IS 'วันที่สั่งซื้อ';
COMMENT ON COLUMN ORDERS.REQUIRED_DATE IS 'วันที่จัดส่ง';
COMMENT ON COLUMN ORDERS.SHIPPED_DATE IS 'วันที่จัดส่งสำเร็จ';
COMMENT ON COLUMN ORDERS.STORE_ID IS 'รหัสร้านค้า';
COMMENT ON COLUMN ORDERS.STAFF_ID IS 'รหัสพนักงานหัวหน้า';

CREATE TABLE ORDER_ITEMS (
	ORDER_ID INT,
	ITEM_ID INT,
	PRODUCT_ID INT NOT NULL,
	QUANTITY INT NOT NULL,
	LIST_PRICE DECIMAL (10, 2) NOT NULL,
	DISCOUNT DECIMAL (4, 2) NOT NULL DEFAULT 0,
	PRIMARY KEY (ORDER_ID, ITEM_ID),
	FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)
);
COMMENT ON COLUMN ORDER_ITEMS.ORDER_ID IS 'รหัสคำสั่งซื้อ';
COMMENT ON COLUMN ORDER_ITEMS.ITEM_ID IS 'ลำดับราการสินค้า';
COMMENT ON COLUMN ORDER_ITEMS.PRODUCT_ID IS 'รหัสสินค้า';
COMMENT ON COLUMN ORDER_ITEMS.QUANTITY IS 'จำนวน';
COMMENT ON COLUMN ORDER_ITEMS.LIST_PRICE IS 'ราคาต่อหน่วย';
COMMENT ON COLUMN ORDER_ITEMS.DISCOUNT IS 'ส่วนลด';

CREATE TABLE STOCKS (
	STORE_ID INT,
	PRODUCT_ID INT,
	QUANTITY INT,
	PRIMARY KEY (STORE_ID, PRODUCT_ID),
	FOREIGN KEY (STORE_ID) REFERENCES STORES (STORE_ID),
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)
);
COMMENT ON COLUMN STOCKS.STORE_ID IS 'รหัสร้านค้า';
COMMENT ON COLUMN STOCKS.PRODUCT_ID IS 'รหัสสินค้า';
COMMENT ON COLUMN STOCKS.QUANTITY IS 'จำนวน';